#
# Autogenerated by Sandesh Compiler (1.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#


# This autogenerated skeleton file illustrates the implementation of
# derived class to handle the sandesh request.


# Create a derived class from "GreenletObjectReq" to handle 
# the sandesh request. Add this derived class "GreenletObjectReq_derived"
# in module GreenletObjectReq_derived.py and add it in your package

class GreenletObjectReq_derived(GreenletObjectReq):

  def __init__(self):
    GreenletObjectReq.__init__(self, greenlet_name=None)

  def handle_request(self):
    # Add your code to handle the "GreenletObjectReq" request
    pass
  
