apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name:
        image:
        ports:
        - containerPort: 80
