#! /usr/bin/python

"""Module to receive packets.
"""
import sys

try:
    # Running from the source repo "test".
    from tcutils.pkgs.Traffic.traffic.utils.daemon import Daemon
    from tcutils.pkgs.Traffic.traffic.utils.logger import get_logger, LOGGER
    from tcutils.pkgs.Traffic.traffic.core.listener import ListenerArgParser, PktListener
    from tcutils.pkgs.Traffic.traffic.utils.globalvars import LOG_LEVEL
except ImportError:
    # Distributed and installed as package
    from traffic.utils.daemon import Daemon
    from traffic.core.listener import ListenerArgParser, PktListener
    from traffic.utils.logger import LOGGER, get_logger
    from traffic.utils.globalvars import LOG_LEVEL

LOGGER = "%s.scripts.recvpkts" % LOGGER
log = get_logger(name=LOGGER, level=LOG_LEVEL)


def poll(name):
        fd = open("/tmp/%s.results" % name, "r")
        results = fd.readlines()
        fd.close()
        return results


class PktRcvDaemon(Daemon):

    def __init__(self, args, pidfile, stdin, stdout, stderr):
        super(PktRcvDaemon, self).__init__(pidfile, stdin, stdout, stderr)
        self.args = args

    def run(self):
        self.listener = PktListener(self.args)
        self.listener.start()

    def stop(self):
        self._stop()
        return poll(self.args.name)


def main():
    args = ListenerArgParser().parse()
    if args.poll:
        return poll(args.name)

    pidfile = '/tmp/%s.pid' % args.name
    if args.stop:
        prefix = "stop"
    else:
        prefix = "start"
    logfile = '/tmp/%s-recvpkts-%s.log' % (prefix, args.name)
    open(logfile, 'w+')
    daemon = PktRcvDaemon(args, pidfile, logfile, logfile, logfile)
    if args.stop:
        return daemon.stop()
    else:
        return daemon.start()


if __name__ == "__main__":
    result = main()
    print result
    sys.exit(0)
