SERVICES_MAP = {'api-server': ['config_api'],
                'schema': ['config_schema'],
                'svc-monitor': ['config_svcmonitor'],
                'device-manager': ['config_devicemgr'],
                'control': ['control_control'],
                'dns': ['control_dns'],
                'named': ['control_named'],
                'analytics-api': ['analytics_api'],
                'alarm-gen': ['analytics_alarm-gen'],
                'query-engine': ['analytics_query-engine'],
                'topology': ['analytics_topology'],
                'collector': ['analytics_collector'],
                'snmp-collector': ['analytics_snmp-collector'],
                'agent': ['contrail-agent', 'vrouter-agent'],
                'webui': ['webui_web'],
                'webui-middleware': ['webui_job'],
                'config-rabbitmq': ['configdatabase_rabbitmq'],
                'config-zookeeper': ['configdatabase_zookeeper'],
                'config-cassandra': ['configdatabase_cassandra'],
                'analytics-kafka': ['analyticsdb_kafka'],
                'analytics-zookeeper': ['analyticsdb_zookeeper'],
                'analytics-cassandra': ['analyticsdb_cassandra'],
                'nova': ['nova_api'],
                'nova-compute': ['nova_compute'],
                'nova-conductor': ['nova_conductor'],
                'nova-scheduler': ['nova_scheduler'],
                'glance': ['glance_api'],
                'rabbitmq': ['rabbitmq'],
                'haproxy': ['haproxy'],
                'keystone': ['keystone'],
                'neutron': ['neutron'],
                'mysql': ['mariadb'],
                'contrail-kube-manager': ['contrail-kube-manager'],
# Added below for backward compatibility and can be removed
# once all deployments move to microservices model
                'controller': ['contrail-controller'],
                'analytics': ['contrail-analytics'],
                'analyticsdb': ['contrail-analyticsdb']
               }
