#
# Autogenerated by Sandesh Compiler (1.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#


# This autogenerated skeleton file illustrates the implementation of
# derived class to handle the sandesh request.


# Create a derived class from "CpuLoadInfoReq" to handle 
# the sandesh request. Add this derived class "CpuLoadInfoReq_derived"
# in module CpuLoadInfoReq_derived.py and add it in your package

class CpuLoadInfoReq_derived(CpuLoadInfoReq):


  def handle_request(self):
    # Add your code to handle the "CpuLoadInfoReq" request
    pass
  
